---
engines:
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
  reek:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
  - "**.css"
exclude_paths:
- config/
- quke_demo_app/public/assets/css/bootstrap.min.css
- quke_demo_app/public/assets/css/ie10-viewport-bug-workaround.css
