dist: trusty

addons:
  sonarcloud:
    organization: "defra"

language: ruby
rvm: 2.4.2
cache: bundler

# Travis CI uses shallow clone to speed up build times, but a truncated SCM
# history may cause issues when SonarCloud computes blame data. To avoid this,
# you can access the full SCM history with `depth: false`
git:
  depth: false

before_install:
  - export TZ=UTC
  - gem install -v 1.17.3 bundler --no-rdoc --no-ri

script:
  - bundle exec rubocop --format=json --out=rubocop-result.json
  - bundle exec rspec
  - sonar-scanner
