sudo: false
language: ruby
rvm:
  - 2.3.1
before_install: gem install bundler -v 1.12.5

# Travis CI clones repositories to a depth of 50 commits, which is only really
# useful if you are performing git operations.
# https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
git:
  depth: 3

# enable Bundler caching
# https://docs.travis-ci.com/user/languages/ruby#Caching-Bundler
cache: bundler

# Using the ability to customise the Travis build to check for 'focus' labels
# i.e. labels used when working on a spec but which we don't want appearing in
# the final commit to master
# Reworking of http://stackoverflow.com/a/30495279/6117745
# If grep returns 0 (match found), test 0 -eq 1 will return 1.
# If grep returns 1 (no match found), test 1 -eq 1 will return 0.
# If grep returns 2 (error), test 2 -eq 1 will return 1.
before_script: >-
  echo "Checking for use of 'focus' labels in specs" && grep -r --include="*_spec.rb" "focus: true" spec/; test $? -eq 1

# This section was added as per https://docs.travis-ci.com/user/code-climate/
# To protect our codeclimate stats rather than adding the Codeclimate API key for ea-area_lookup
# in the open we used this guide https://docs.travis-ci.com/user/encryption-keys/ to encryt the
# value. Essentially install travis gem, then run `travis encrypt <my_code_climate_api_key>`
addons:
  code_climate:
    repo_token:
      secure: "TULHMA2Zmp0ntRGBVbLAJqSa9XWSm6gOunAEESbEUZYXt9eTuwvCHLOk1kz/EPq+3s60JokYOpGPB5iTGY4HxS/3gAmNR1Eo1smHqXDXqHjDb0X1l+w4mPUtdTRxTzzYJCaGkDptyCRv7p55LstfnZWlseQjlO1Er1TvQzzOb0XpsM+bO1ZiFNYZQcK8lAp2IrEcZNi0AEr96djc8vFymhV8ZocK39FythTwUBsw4eHitdFRTJwHZUUToatzN4R2Tl8rRNvj+xL3SmTqF1QZQovBGluuiewR0sddzU0vfQEB9tg7v+sMOoIK5ANYJ8SmabmsMa5zjnKEpxK0tgyD/vN9VWNH8qTY8yrGVg1wkQUmabV+1XSXNeHHuvHtlGp76OOqvNVCzlqspn0XsiS0TmcFhQlnNnhfQqFXXaMkt3ToPWDZfiXdmm5EMP5tqkNMhu/OtF1r99k7LbmDA0SMm3OK4TqTDLYDiDYJpwGYyWbWh9eCBgSyOzTW0sKvu0cxjznFd7NVx845lcfWLcDYGAyLEXm1WE1uULRjJgzabi4MkTz0DPBRxFP0STfXf96+NGxkSnKI5akQgyO4I+ITLS07pU6G16lcc8LNhqXFWdMVvPXSqzzLNqcV9U6zIyWaaf1whBO7/RPks3hKWw9GMwun49pR6GJ2wLeMnbnVsAQ="

deploy:
  provider: rubygems
  api_key:
    secure: "mrNfo3ZlO4wtr7fp751jltjKZcWeFXLCxxVDHqJVnkdAKpDcbo99Phlq9+fh5Q/o8gIJ4jKQybvr/Zu5t8mrWYJKKLlsUi3UThJG5hOg64ynJKy3jqtU45uCGOc33oBhQAqHTfDI+DZxQTGs2TepoqdyxsSzki
s9TRj+qyeE2HSO+yz5Qyjwql6o5k9xP82uBFaQI0WKqKdTtdNFv5LZ3EZaRWtyM/jGsunaNAYscDOl3cYN1sXlq+wfCTRvjMGmcppdbsaczQNQdIkXBPZEkydO7FdnSwUFuwm30BP0OBks5myB7oHWbbe0p/YRsUbjLF0dVfn
AlSERSwhkpMOU1BpK4/vwPBoR8yzgfZG4UZAZQ6hCMtRj+2usKWcI4buryeD+iPDrkVX9FjziOC3OFSbMzo/ojYlkLjvvXuUcTAmWZr0V/VP1x7RAiHNA+Y7EqYRJFJcEE5Av7Yn+hgi8fUtLyiSDLOb4bGJ2fe9R3YeZQ1ge
pvnarjriXfNZul3K1tP21/oVeXwCRuOjPMxwUmEsPCCjdIu/44U5CvGRbaqJXAqYJm71u+Y96RfkjytRnLmAc13nIBiFCUqUyoab4GIsy9AZ4TzE9ROGwLTC3y05gMVlYVJk4GTtVCjJwqNB2LWRXo/PseWaDdRZYmnNTr5wI
kB5wbWRtEYUdIOb70c="
  gem: quke
  on:
    tags: true
    repo: DEFRA/quke
