# frozen_string_literal: true

# Add support to quke to run the webdrivers rake tasks from host project
# https://github.com/titusfortner/webdrivers#rake-tasks
#
# An acceptance test project that has quke as a dependency can then do the
# following to access these rake tasks directly
#
#   # Add to project's `Rakefile`
#   require "quke"
#   load "quke/Rakefile"
#
require "webdrivers"
load "webdrivers/Rakefile"
