# This file allows us to define profiles for how to run cucumber.
# Generally you create a 'default' profile that is used when you just call 'bundle exec cucumber'.
# To use the other profiles you would call 'bundle exec cucumber -p demo'.
# Some tags are already defined by cucumber like WIP (work in progress) but the idea is you create
# your own tags and append them either to features (in which case they are automatically applied
# to the underlying scenarios) or directly to the scenarios.
# You can then create profiles which run them or exclude them, depending on requirements.
#
# For more details see
# https://github.com/cucumber/cucumber/wiki/Tags
# https://github.com/cucumber/cucumber/wiki/cucumber.yml
---
# Format pretty is actually the default but is specified to make it clear it is being used.
# Tags with a ~ in front are to be excluded, else they are included.
default: --format pretty --tags ~@wip --tags ~@quke --tags ~@quke_browserstack
quke: --format pretty --tags @quke --tags ~@wip --tags ~@quke_browserstack
quke_browserstack: --format pretty --tags @quke_browserstack --tags ~@wip --tags ~@quke
